channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - dagshub==0.6.3
  - mlflow==2.22.2
  - cloudpickle==3.1.0
  - numpy==2.2.1
  - pandas==2.2.3
  - psutil==5.9.0
  - scikit-learn==1.6.0
  - scipy==1.14.1
  - joblib==1.5.2
  - matplotlib==3.10.6
  - plotly==6.3.0
  - seaborn==0.13.2
name: mlflow-env
