channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=23.2.1
- pip:
  - mlflow==3.4.0
  - catboost==1.2.8
  - cloudpickle==3.1.1
  - lightgbm==4.6.0
  - matplotlib==3.10.6
  - numpy==2.3.3
  - pandas==2.3.2
  - pyarrow==21.0.0
  - scikit-learn==1.7.2
  - scipy==1.16.2
  - xgboost==3.0.5
name: mlflow-env
