name: SpaceShip Titanic Preprocessing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12.7"
          environment-file: conda.yaml

      - name: Run preprocessing and training script
        shell: bash -l {0}
        run: |
          python automate_Muhammad_Raqwan_kauthar.py spaceship_titanic_raw/data.csv 

      - name: List mlruns directory
        run: |
          ls -R mlruns

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          # Perintah ini mencari direktori run terbaru di dalam mlruns/0/
          LATEST_RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=${LATEST_RUN_ID}" >> "$GITHUB_ENV"
          echo "Latest run_id found: ${LATEST_RUN_ID}"
      
      - name: Build Docker Image from Model
        run: |
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "spaceship_titanic_preprocessing" 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag spaceship_titanic_preprocessing ${{ secrets.DOCKER_HUB_USERNAME }}/spaceship_titanic_preprocessing:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spaceship_titanic_preprocessing:latest