name: CI/CD MLflow with SageMaker Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Conda environment from conda.yaml
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12.7"
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          
      - name: Run mlflow project
        run: |
          cd MLProject
          mlflow run . --env-manager=local
      
      - name: Get latest MLflow run_id
        working-directory: ./MLProject
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
          
      - name: Build Docker Model
        working-directory: ./MLProject
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "spaceship_titanic_modelling" 

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        working-directory: ./MLProject
        run: |
          docker tag spaceship_titanic_modelling ${{ secrets.DOCKER_HUB_USERNAME }}/spaceship_titanic_modelling:latest

      - name: Push Docker Image
        working-directory: ./MLProject
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spaceship_titanic_modelling:latest
